Oro\Bundle\AkeneoBundle\Entity\AkeneoSettings:
  properties:
    url:
      - NotBlank: ~
      - Url: ~
    clientId:
      - NotBlank: ~
    secret:
      - NotBlank: ~
    username:
      - NotBlank: ~
    password:
      - NotBlank: ~
    akeneoActiveChannel:
      - NotBlank: ~
    productUnit:
      - NotBlank: ~
    productUnitPrecision:
      - NotBlank: ~
